//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4959
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 6/7/2011 3:23:46 PM
namespace HRHiringTool.DataAccess.Model
{
    
    /// <summary>
    /// There are no comments for HRHiringToolContainer in the schema.
    /// </summary>
    public partial class HRHiringToolContainer : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new HRHiringToolContainer object using the connection string found in the 'HRHiringToolContainer' section of the application configuration file.
        /// </summary>
        public HRHiringToolContainer() : 
                base("name=HRHiringToolContainer", "HRHiringToolContainer")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new HRHiringToolContainer object.
        /// </summary>
        public HRHiringToolContainer(string connectionString) : 
                base(connectionString, "HRHiringToolContainer")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new HRHiringToolContainer object.
        /// </summary>
        public HRHiringToolContainer(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "HRHiringToolContainer")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Entity1Set in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Entity1> Entity1Set
        {
            get
            {
                if ((this._Entity1Set == null))
                {
                    this._Entity1Set = base.CreateQuery<Entity1>("[Entity1Set]");
                }
                return this._Entity1Set;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Entity1> _Entity1Set;
        /// <summary>
        /// There are no comments for Entity1Set in the schema.
        /// </summary>
        public void AddToEntity1Set(Entity1 entity1)
        {
            base.AddObject("Entity1Set", entity1);
        }
    }
    /// <summary>
    /// There are no comments for HRHiringTool.Entity1 in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HRHiringTool", Name="Entity1")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Entity1 : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Entity1 object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        public static Entity1 CreateEntity1(int id)
        {
            Entity1 entity1 = new Entity1();
            entity1.Id = id;
            return entity1;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
    }
}
